language: node_js
node_js:
- '12'
deploy:
  provider: lambda
  function_name: "charlascrum"
  region: "eu-west-1"
  role: "arn:aws:iam::764255565061:role/service-role/charlascrum-role-8u4wkff3"
  runtime: "nodejs12.x"
  handler_name: "handler"
