language: node_js
node_js:
- '8.9.1'
deploy:
  provider: heroku
  api_key:
    secure: rjlPU7fzimp4WL7AuW1p/MC0dIh6FI0PYoTzXAB712NwyPN0OpZQ8zIwPMfqXzqVp2JuSBV5OMsJEDq1fTeq+kVtYKvp0oPSiur3FtTl1Wxbf9HqC1qel/2wMadjb3TAZp98gx6QbhnHw7YHu6h2EMllw8Pf1lUvBfRCPtaUwm0W05ONfSuxx5eTuuvyzt5zumGNmkfRW3nm4KutP07qsjNc2KCL7LPcuZkcfkKBo86tUHcd6cOywQeV58OI1hmj2QW6tIhQToHbgj2PXxH9tZ7WNIqtjSvcNUKOUSelZBtn93ODwRsRvpfz0zYbFw7ETvGm2Ei5VA78SCaHazZRh+GsrO3DAUgFQ8OTc3eHNnMUT/cfi1XMhHvTgSFsLy+u8Vf1gtp+EVE/o9uerlftrLRFwVE5vCMZC2rTKs2I1cy+WmSEEPjln2vroPVS/3pt2QDt1el1xyyXzy5Da2jINZirIDG8YcfjmJ9me6fratTLfZ65wcEHaJcnpQ9OMmOZlysCsAltwJ3wVo7hlxZNq8WhTDJraeHrcgJLKLXD8td20Y0R+TOsK2Eq8Okg3KT4B5E6xUwWQiRgdzenWLdzjXjdMhFJ1TUm3IA/uJu6BY0zpAUDVPNaf7HGn+wR2YaZ3wvUk0Zw67IdgoHAvp/ukBJZh5LSHO/Ak/ntjqIAoUo=
  app: github-scrum-test
  on:
    repo: pedroprieto/test_presentacion_github_scrum
  skip_cleanup: true
