language: node_js
node_js:
- '0.10'
deploy:
  provider: openshift
  user: pedroprieto
  password:
    secure: MhEw8fqDO16epjAL89RLl8olsqMNNufLVq9ykNDynReQ3Os79ZI8Wlnx6VQGJizoGHjCtX+7FgwEh/oluXYWIM4ab4dDoKOvfrMrg97sycdh3dRExkYia/oQxDsPAkXgOGiXuKQZ9bfk5JQMlS0znxo+V7gNRqoqPh1ZUsZdLyfSmjvykfWbM1U9v3uqayiGkxKmOV/MR6BoTGQNBYqc8vP3T1271buvPOsMRsvpcRgF3DmLzJ1CoJ0OISpN0PFR85luQ8iLDx2MOQcRK7t31IQJlG+fIiqns59j9NWWdbpzeYb787/ofhn2Cz1Flaudtp49jMB45XbOeOrMVPTJK+iGiYlUM9kQ+qilstzuoGKlTKFk8XYD4Yqx/MHEFplOpNhZgyBwEMBpgtVRvJMAzQYJrOmCqGeQ1yqj5NEh21rzk9BAW9ywd4+YavNj1BNsw5/WTfGRG7w9VTPoO4LGMMvug8E53tKcNMI3i/kgUwhkcu7RTF5uiBQYuKAr/zjcpEvwoBv8xdk/J5xH6qPXW4NrAYH83QANjJsyrKqui9iBB+hkV/31SGgzU7zBOAhVQvpuymnkeKIbrOrQOo8BXOR6WGdhKtnWTwpTNDpJiea39bA7RJ0+E13Obcb/Vs39i4uZuDfsHos0GnYQYRDpyKkZBrkkhdw3lKFEAXvFuno=
  app: test
  domain: pedroprieto.rhcloud.com
  on:
    repo: pedroprieto/test_presentacion_github_scrum
