language: node_js
node_js:
- '8.9.1'
deploy:
  provider: heroku
  api_key:
    secure: dcB56Csm/fb2zDjeWb+5kqvVha180jb4YYiTMkaYXT6u3+s7q8on03vSejoyIl4cdEJqgYf2hOROt7odQtqzo1rwhTgDPtZw267HQJ59+HxwwFsvOaCQtZMqEsmDJwLSIx+OD9YK4g1seGai36E8tr64kh3E6Ri09BPZPoKaMSGgy1pHaDqtJwYUvQovclii0rhMaAH9+WqXfyn9GV/YJcNo9IZPYf7176yb9ZCECY+AjKa75OOQFLNjKVgaS+/Jy/Lmv7QCaMaWOQNU7Q++gJcHTUjWuCC/aIIN9IzX0fGqQMm6ohD9evIJcpiq+my/Igqw4lVwPTnIfuq95U9ddeEwv6foqF1W/OU7DQvbREzjqCFLdTXp4VIPnsAnmCHdYlINjXCb4dEeHgwdaRYKzPlqZ+U5NjyyvXCvVkDj/0s7R01XDJH6GHyVUS+wt5qQT69GMbgTn9z71K98qcvOa5uQ5QmlsGv/8fK0jjtlAtc7ctvG6uFRxf1f9jHTIPA0gTcFPh4qdvcvExtif+QKMdmozm0/afHX5t5fibenFfN8hB8PgQ6XnpS/ui2KQyCAoNlI+RyJfhHQHUvKJrIWEX/eCF1CYL8trCRda8jf9A1X1ilzpEv2vXOI7Q+6YfAI/S1YZ6odjSPHhE6HGaa7rjVe5cFtdTGT3AgG6/uo6Cs=
  app: github-scrum-test
  on:
    repo: pedroprieto/test_presentacion_github_scrum
  skip_cleanup: true
